workflows:
  my-workflow:
    name: My workflow name
    scripts:
    - name: iOS test
      script: xcodebuild -project SwiftUI.xcodeproj -scheme SwiftUI -destination 'platform:iOS Simulator, id:8DAAC55E-9200-43DF-B84E-1E8A4595C8B2, OS:14.4, name:iPad (8th generation)' test
    - name: Increment build number
      script: agvtool new-version -all $(($BUILD_NUMBER +1))