workflows:
  my-workflow:
    name: My workflow name
    scripts:
    - name: iOS test
      script: xcodebuild -project SwiftUI.xcodeproj -scheme SwiftUI -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.3' test
    - name: Increment build number
      script: agvtool new-version -all $(($BUILD_NUMBER +1))